package comi.entities;
// Generated Jun 9, 2019 4:54:54 PM by Hibernate Tools 5.1.7.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * BankId generated by hbm2java
 */
@Embeddable
public class BankId implements java.io.Serializable {

	private int id;
	private String bankaccount;
	private String name;
	private String department;
	private int vendorid;

	public BankId() {
	}

	public BankId(int id, String bankaccount, String name, String department, int vendorid) {
		this.id = id;
		this.bankaccount = bankaccount;
		this.name = name;
		this.department = department;
		this.vendorid = vendorid;
	}

	@Column(name = "id", nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "bankaccount", nullable = false, length = 250)
	public String getBankaccount() {
		return this.bankaccount;
	}

	public void setBankaccount(String bankaccount) {
		this.bankaccount = bankaccount;
	}

	@Column(name = "name", nullable = false, length = 250)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "department", nullable = false, length = 250)
	public String getDepartment() {
		return this.department;
	}

	public void setDepartment(String department) {
		this.department = department;
	}

	@Column(name = "vendorid", nullable = false)
	public int getVendorid() {
		return this.vendorid;
	}

	public void setVendorid(int vendorid) {
		this.vendorid = vendorid;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof BankId))
			return false;
		BankId castOther = (BankId) other;

		return (this.getId() == castOther.getId())
				&& ((this.getBankaccount() == castOther.getBankaccount())
						|| (this.getBankaccount() != null && castOther.getBankaccount() != null
								&& this.getBankaccount().equals(castOther.getBankaccount())))
				&& ((this.getName() == castOther.getName()) || (this.getName() != null && castOther.getName() != null
						&& this.getName().equals(castOther.getName())))
				&& ((this.getDepartment() == castOther.getDepartment()) || (this.getDepartment() != null
						&& castOther.getDepartment() != null && this.getDepartment().equals(castOther.getDepartment())))
				&& (this.getVendorid() == castOther.getVendorid());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getId();
		result = 37 * result + (getBankaccount() == null ? 0 : this.getBankaccount().hashCode());
		result = 37 * result + (getName() == null ? 0 : this.getName().hashCode());
		result = 37 * result + (getDepartment() == null ? 0 : this.getDepartment().hashCode());
		result = 37 * result + this.getVendorid();
		return result;
	}

}
