package comi.entities;
// Generated Jun 9, 2019 4:54:54 PM by Hibernate Tools 5.1.7.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Bank generated by hbm2java
 */
@Entity
@Table(name = "bank", catalog = "multivendor")
public class Bank implements java.io.Serializable {

	private BankId id;
	private Vendor vendor;

	public Bank() {
	}

	public Bank(BankId id, Vendor vendor) {
		this.id = id;
		this.vendor = vendor;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "id", column = @Column(name = "id", nullable = false)),
			@AttributeOverride(name = "bankaccount", column = @Column(name = "bankaccount", nullable = false, length = 250)),
			@AttributeOverride(name = "name", column = @Column(name = "name", nullable = false, length = 250)),
			@AttributeOverride(name = "department", column = @Column(name = "department", nullable = false, length = 250)),
			@AttributeOverride(name = "vendorid", column = @Column(name = "vendorid", nullable = false)) })
	public BankId getId() {
		return this.id;
	}

	public void setId(BankId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "vendorid", nullable = false, insertable = false, updatable = false)
	public Vendor getVendor() {
		return this.vendor;
	}

	public void setVendor(Vendor vendor) {
		this.vendor = vendor;
	}

}
