package comi.entities;
// Generated Jun 9, 2019 4:54:54 PM by Hibernate Tools 5.1.7.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Contract generated by hbm2java
 */
@Entity
@Table(name = "contract", catalog = "multivendor")
public class Contract implements java.io.Serializable {

	private ContractId id;
	private Package package_;
	private Vendor vendor;

	public Contract() {
	}

	public Contract(ContractId id, Package package_, Vendor vendor) {
		this.id = id;
		this.package_ = package_;
		this.vendor = vendor;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "id", column = @Column(name = "id", nullable = false)),
			@AttributeOverride(name = "description", column = @Column(name = "description", nullable = false, length = 250)),
			@AttributeOverride(name = "duration", column = @Column(name = "duration", nullable = false)),
			@AttributeOverride(name = "type", column = @Column(name = "type", nullable = false, length = 250)),
			@AttributeOverride(name = "status", column = @Column(name = "status", nullable = false, length = 250)),
			@AttributeOverride(name = "vendorid", column = @Column(name = "vendorid", nullable = false)),
			@AttributeOverride(name = "unitPrice", column = @Column(name = "unitPrice", nullable = false, precision = 22, scale = 0)),
			@AttributeOverride(name = "packageid", column = @Column(name = "packageid", nullable = false)) })
	public ContractId getId() {
		return this.id;
	}

	public void setId(ContractId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "packageid", nullable = false, insertable = false, updatable = false)
	public Package getPackage() {
		return this.package_;
	}

	public void setPackage(Package package_) {
		this.package_ = package_;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "vendorid", nullable = false, insertable = false, updatable = false)
	public Vendor getVendor() {
		return this.vendor;
	}

	public void setVendor(Vendor vendor) {
		this.vendor = vendor;
	}

}
