package comi.entities;
// Generated Jun 9, 2019 4:54:54 PM by Hibernate Tools 5.1.7.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ContractId generated by hbm2java
 */
@Embeddable
public class ContractId implements java.io.Serializable {

	private int id;
	private String description;
	private int duration;
	private String type;
	private String status;
	private int vendorid;
	private double unitPrice;
	private int packageid;

	public ContractId() {
	}

	public ContractId(int id, String description, int duration, String type, String status, int vendorid,
			double unitPrice, int packageid) {
		this.id = id;
		this.description = description;
		this.duration = duration;
		this.type = type;
		this.status = status;
		this.vendorid = vendorid;
		this.unitPrice = unitPrice;
		this.packageid = packageid;
	}

	@Column(name = "id", nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "description", nullable = false, length = 250)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "duration", nullable = false)
	public int getDuration() {
		return this.duration;
	}

	public void setDuration(int duration) {
		this.duration = duration;
	}

	@Column(name = "type", nullable = false, length = 250)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "status", nullable = false, length = 250)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "vendorid", nullable = false)
	public int getVendorid() {
		return this.vendorid;
	}

	public void setVendorid(int vendorid) {
		this.vendorid = vendorid;
	}

	@Column(name = "unitPrice", nullable = false, precision = 22, scale = 0)
	public double getUnitPrice() {
		return this.unitPrice;
	}

	public void setUnitPrice(double unitPrice) {
		this.unitPrice = unitPrice;
	}

	@Column(name = "packageid", nullable = false)
	public int getPackageid() {
		return this.packageid;
	}

	public void setPackageid(int packageid) {
		this.packageid = packageid;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ContractId))
			return false;
		ContractId castOther = (ContractId) other;

		return (this.getId() == castOther.getId())
				&& ((this.getDescription() == castOther.getDescription())
						|| (this.getDescription() != null && castOther.getDescription() != null
								&& this.getDescription().equals(castOther.getDescription())))
				&& (this.getDuration() == castOther.getDuration())
				&& ((this.getType() == castOther.getType()) || (this.getType() != null && castOther.getType() != null
						&& this.getType().equals(castOther.getType())))
				&& ((this.getStatus() == castOther.getStatus()) || (this.getStatus() != null
						&& castOther.getStatus() != null && this.getStatus().equals(castOther.getStatus())))
				&& (this.getVendorid() == castOther.getVendorid()) && (this.getUnitPrice() == castOther.getUnitPrice())
				&& (this.getPackageid() == castOther.getPackageid());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getId();
		result = 37 * result + (getDescription() == null ? 0 : this.getDescription().hashCode());
		result = 37 * result + this.getDuration();
		result = 37 * result + (getType() == null ? 0 : this.getType().hashCode());
		result = 37 * result + (getStatus() == null ? 0 : this.getStatus().hashCode());
		result = 37 * result + this.getVendorid();
		result = 37 * result + (int) this.getUnitPrice();
		result = 37 * result + this.getPackageid();
		return result;
	}

}
