package comi.entities;
// Generated Jul 8, 2019 8:31:00 PM by Hibernate Tools 5.1.7.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * District generated by hbm2java
 */
@Entity
@Table(name = "district", catalog = "multivendor")
public class District implements java.io.Serializable {

	private Integer id;
	private Stateorprovince stateorprovince;
	private String name;
	private String type;
	private String location;
	private Set<Personinfo> personinfos = new HashSet<Personinfo>(0);
	private Set<Shipmentdetail> shipmentdetails = new HashSet<Shipmentdetail>(0);
	private Set<Warehouse> warehouses = new HashSet<Warehouse>(0);

	public District() {
	}

	public District(Stateorprovince stateorprovince, String name, String type, String location) {
		this.stateorprovince = stateorprovince;
		this.name = name;
		this.type = type;
		this.location = location;
	}

	public District(Stateorprovince stateorprovince, String name, String type, String location,
			Set<Personinfo> personinfos, Set<Shipmentdetail> shipmentdetails, Set<Warehouse> warehouses) {
		this.stateorprovince = stateorprovince;
		this.name = name;
		this.type = type;
		this.location = location;
		this.personinfos = personinfos;
		this.shipmentdetails = shipmentdetails;
		this.warehouses = warehouses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "StateOrProvinceId", nullable = false)
	public Stateorprovince getStateorprovince() {
		return this.stateorprovince;
	}

	public void setStateorprovince(Stateorprovince stateorprovince) {
		this.stateorprovince = stateorprovince;
	}

	@Column(name = "name", nullable = false, length = 250)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "type", nullable = false, length = 250)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "location", nullable = false, length = 250)
	public String getLocation() {
		return this.location;
	}

	public void setLocation(String location) {
		this.location = location;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "district")
	public Set<Personinfo> getPersoninfos() {
		return this.personinfos;
	}

	public void setPersoninfos(Set<Personinfo> personinfos) {
		this.personinfos = personinfos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "district")
	public Set<Shipmentdetail> getShipmentdetails() {
		return this.shipmentdetails;
	}

	public void setShipmentdetails(Set<Shipmentdetail> shipmentdetails) {
		this.shipmentdetails = shipmentdetails;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "district")
	public Set<Warehouse> getWarehouses() {
		return this.warehouses;
	}

	public void setWarehouses(Set<Warehouse> warehouses) {
		this.warehouses = warehouses;
	}

}
