package comi.entities;
// Generated Jun 9, 2019 4:54:54 PM by Hibernate Tools 5.1.7.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Hoadon generated by hbm2java
 */
@Entity
@Table(name = "hoadon", catalog = "examjava")
public class Hoadon implements java.io.Serializable {

	private Integer mahd;
	private String tenhd;
	private Date ngaylap;
	private String httt;
	private Byte trangthai;
	private String username;

	public Hoadon() {
	}

	public Hoadon(String tenhd, Date ngaylap, String httt, Byte trangthai, String username) {
		this.tenhd = tenhd;
		this.ngaylap = ngaylap;
		this.httt = httt;
		this.trangthai = trangthai;
		this.username = username;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "mahd", unique = true, nullable = false)
	public Integer getMahd() {
		return this.mahd;
	}

	public void setMahd(Integer mahd) {
		this.mahd = mahd;
	}

	@Column(name = "tenhd", length = 50)
	public String getTenhd() {
		return this.tenhd;
	}

	public void setTenhd(String tenhd) {
		this.tenhd = tenhd;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ngaylap", length = 26)
	public Date getNgaylap() {
		return this.ngaylap;
	}

	public void setNgaylap(Date ngaylap) {
		this.ngaylap = ngaylap;
	}

	@Column(name = "httt", length = 50)
	public String getHttt() {
		return this.httt;
	}

	public void setHttt(String httt) {
		this.httt = httt;
	}

	@Column(name = "trangthai")
	public Byte getTrangthai() {
		return this.trangthai;
	}

	public void setTrangthai(Byte trangthai) {
		this.trangthai = trangthai;
	}

	@Column(name = "username", length = 50)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

}
