package comi.entities;
// Generated Jun 9, 2019 4:54:54 PM by Hibernate Tools 5.1.7.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Package generated by hbm2java
 */
@Entity
@Table(name = "package", catalog = "multivendor")
public class Package implements java.io.Serializable {

	private Integer id;
	private String name;
	private String description;
	private double price;
	private Set<Contract> contracts = new HashSet<Contract>(0);

	public Package() {
	}

	public Package(String name, String description, double price) {
		this.name = name;
		this.description = description;
		this.price = price;
	}

	public Package(String name, String description, double price, Set<Contract> contracts) {
		this.name = name;
		this.description = description;
		this.price = price;
		this.contracts = contracts;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false, length = 250)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "description", nullable = false, length = 250)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "price", nullable = false, precision = 22, scale = 0)
	public double getPrice() {
		return this.price;
	}

	public void setPrice(double price) {
		this.price = price;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "package")
	public Set<Contract> getContracts() {
		return this.contracts;
	}

	public void setContracts(Set<Contract> contracts) {
		this.contracts = contracts;
	}

}
