package comi.entities;
// Generated Jul 8, 2019 8:31:00 PM by Hibernate Tools 5.1.7.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import java.util.HashSet;
import java.util.Set;

/**
 * Payment generated by hbm2java
 */
@Entity
@Table(name = "payment", catalog = "multivendor")
public class Payment implements java.io.Serializable {

	private Integer id;
	private String name;
	private String description;
	private Set<Saleorder> saleorders = new HashSet<Saleorder>(0);

	public Payment() {
	}

	public Payment(String name, String description) {
		this.name = name;
		this.description = description;
	}

	public Payment(String name, String description, Set<Saleorder> saleorders) {
		this.name = name;
		this.description = description;
		this.saleorders = saleorders;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false, length = 250)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "description", nullable = false, length = 250)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "payment")
	public Set<Saleorder> getSaleorders() {
		return this.saleorders;
	}

	public void setSaleorders(Set<Saleorder> saleorders) {
		this.saleorders = saleorders;
	}

}
