package comi.entities;
// Generated Jun 9, 2019 4:54:54 PM by Hibernate Tools 5.1.7.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Productdetail generated by hbm2java
 */
@Entity
@Table(name = "productdetail", catalog = "multivendor")
public class Productdetail implements java.io.Serializable {

	private Integer id;
	private Product product;
	private int photo;
	private int description;

	public Productdetail() {
	}

	public Productdetail(Product product, int photo, int description) {
		this.product = product;
		this.photo = photo;
		this.description = description;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "productid", nullable = false)
	public Product getProduct() {
		return this.product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

	@Column(name = "photo", nullable = false)
	public int getPhoto() {
		return this.photo;
	}

	public void setPhoto(int photo) {
		this.photo = photo;
	}

	@Column(name = "description", nullable = false)
	public int getDescription() {
		return this.description;
	}

	public void setDescription(int description) {
		this.description = description;
	}

}
