package comi.entities;
// Generated Jun 15, 2019 5:07:07 PM by Hibernate Tools 5.1.7.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Product generated by hbm2java
 */
@Entity
@Table(name = "product", catalog = "multivendor")
public class Product implements java.io.Serializable {

	private Integer id;
	private Category category;
	private String name;
	private String description;
	private int quantity;
	private double unitprice;
	private String brand;
	private Set<Comment> comments = new HashSet<Comment>(0);
	private Set<Productdetail> productdetails = new HashSet<Productdetail>(0);
	private Set<Saleorderdetail> saleorderdetails = new HashSet<Saleorderdetail>(0);

	public Product() {
	}

	public Product(Category category, String name, String description, int quantity, double unitprice,
			String brand) {
		this.category = category;
		this.name = name;
		this.description = description;
		this.quantity = quantity;
		this.unitprice = unitprice;
		this.brand = brand;
	}

	public Product(Category category, String name, String description, int quantity, double unitprice,
			String brand, Set<Comment> comments, Set<Productdetail> productdetails,
			Set<Saleorderdetail> saleorderdetails) {
		this.category = category;
		this.name = name;
		this.description = description;
		this.quantity = quantity;
		this.unitprice = unitprice;
		this.brand = brand;
		this.comments = comments;
		this.productdetails = productdetails;
		this.saleorderdetails = saleorderdetails;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "categoryid", nullable = false)
	public Category getCategory() {
		return this.category;
	}

	public void setCategory(Category category) {
		this.category = category;
	}

	@Column(name = "name", nullable = false, length = 250)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "description", nullable = false, length = 250)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "quantity", nullable = false)
	public int getQuantity() {
		return this.quantity;
	}

	public void setQuantity(int quantity) {
		this.quantity = quantity;
	}

	@Column(name = "unitprice", nullable = false, precision = 22, scale = 0)
	public double getUnitprice() {
		return this.unitprice;
	}

	public void setUnitprice(double unitprice) {
		this.unitprice = unitprice;
	}

	@Column(name = "brand", nullable = false, length = 250)
	public String getBrand() {
		return this.brand;
	}

	public void setBrand(String brand) {
		this.brand = brand;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "product")
	public Set<Comment> getComments() {
		return this.comments;
	}

	public void setComments(Set<Comment> comments) {
		this.comments = comments;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "product", cascade = CascadeType.ALL)
	public Set<Productdetail> getProductdetails() {
		return this.productdetails;
	}

	public void setProductdetails(Set<Productdetail> productdetails) {
		this.productdetails = productdetails;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "product")
	public Set<Saleorderdetail> getSaleorderdetails() {
		return this.saleorderdetails;
	}

	public void setSaleorderdetails(Set<Saleorderdetail> saleorderdetails) {
		this.saleorderdetails = saleorderdetails;
	}

}
