package comi.entities;
// Generated Jun 15, 2019 5:07:07 PM by Hibernate Tools 5.1.7.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Shipper generated by hbm2java
 */
@Entity
@Table(name = "shipper", catalog = "multivendor")
public class Shipper implements java.io.Serializable {

	private Integer id;
	private String company;
	private String contactname;
	private String contactphone;
	private Set<Saleorder> saleorders = new HashSet<Saleorder>(0);

	public Shipper() {
	}

	public Shipper(String company, String contactname, String contactphone) {
		this.company = company;
		this.contactname = contactname;
		this.contactphone = contactphone;
	}

	public Shipper(String company, String contactname, String contactphone, Set<Saleorder> saleorders) {
		this.company = company;
		this.contactname = contactname;
		this.contactphone = contactphone;
		this.saleorders = saleorders;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "company", nullable = false, length = 250)
	public String getCompany() {
		return this.company;
	}

	public void setCompany(String company) {
		this.company = company;
	}

	@Column(name = "contactname", nullable = false, length = 250)
	public String getContactname() {
		return this.contactname;
	}

	public void setContactname(String contactname) {
		this.contactname = contactname;
	}

	@Column(name = "contactphone", nullable = false, length = 15)
	public String getContactphone() {
		return this.contactphone;
	}

	public void setContactphone(String contactphone) {
		this.contactphone = contactphone;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "shipper")
	public Set<Saleorder> getSaleorders() {
		return this.saleorders;
	}

	public void setSaleorders(Set<Saleorder> saleorders) {
		this.saleorders = saleorders;
	}

}
