package comi.entities;
// Generated Jun 15, 2019 5:07:07 PM by Hibernate Tools 5.1.7.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Shipmentdetail generated by hbm2java
 */
@Entity
@Table(name = "shipmentdetail", catalog = "multivendor")
public class Shipmentdetail implements java.io.Serializable {

	private Integer id;
	private District district;
	private Saleorder saleorder;
	private String firstname;
	private String lastname;
	private String phone;
	private String email;
	private String shiptoaddress;
	private String shiptostreet;

	public Shipmentdetail() {
	}

	public Shipmentdetail(District district, Saleorder saleorder, String firstname, String lastname, String phone,
			String email, String shiptoaddress, String shiptostreet) {
		this.district = district;
		this.saleorder = saleorder;
		this.firstname = firstname;
		this.lastname = lastname;
		this.phone = phone;
		this.email = email;
		this.shiptoaddress = shiptoaddress;
		this.shiptostreet = shiptostreet;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "districtid", nullable = false)
	public District getDistrict() {
		return this.district;
	}

	public void setDistrict(District district) {
		this.district = district;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "saleid", nullable = false)
	public Saleorder getSaleorder() {
		return this.saleorder;
	}

	public void setSaleorder(Saleorder saleorder) {
		this.saleorder = saleorder;
	}

	@Column(name = "firstname", nullable = false, length = 250)
	public String getFirstname() {
		return this.firstname;
	}

	public void setFirstname(String firstname) {
		this.firstname = firstname;
	}

	@Column(name = "lastname", nullable = false, length = 250)
	public String getLastname() {
		return this.lastname;
	}

	public void setLastname(String lastname) {
		this.lastname = lastname;
	}

	@Column(name = "phone", nullable = false, length = 15)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Column(name = "email", nullable = false, length = 150)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "shiptoaddress", nullable = false, length = 250)
	public String getShiptoaddress() {
		return this.shiptoaddress;
	}

	public void setShiptoaddress(String shiptoaddress) {
		this.shiptoaddress = shiptoaddress;
	}

	@Column(name = "shiptostreet", nullable = false, length = 250)
	public String getShiptostreet() {
		return this.shiptostreet;
	}

	public void setShiptostreet(String shiptostreet) {
		this.shiptostreet = shiptostreet;
	}

}
