package comi.entities;
// Generated Jun 15, 2019 5:07:07 PM by Hibernate Tools 5.1.7.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Supplier generated by hbm2java
 */
@Entity
@Table(name = "supplier", catalog = "multivendor")
public class Supplier implements java.io.Serializable {

	private Integer id;
	private Supplier supplier;
	private String name;
	private String taxnumber;
	private String type;
	private String description;
	private Set<Bank> banks = new HashSet<Bank>(0);
	private Set<Supplier> suppliers = new HashSet<Supplier>(0);
	private Set<Warehouse> warehouses = new HashSet<Warehouse>(0);

	public Supplier() {
	}

	public Supplier(Supplier supplier, String name, String taxnumber, String type, String description) {
		this.supplier = supplier;
		this.name = name;
		this.taxnumber = taxnumber;
		this.type = type;
		this.description = description;
	}

	public Supplier(Supplier supplier, String name, String taxnumber, String type, String description, Set<Bank> banks,
			Set<Supplier> suppliers, Set<Warehouse> warehouses) {
		this.supplier = supplier;
		this.name = name;
		this.taxnumber = taxnumber;
		this.type = type;
		this.description = description;
		this.banks = banks;
		this.suppliers = suppliers;
		this.warehouses = warehouses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "userid", nullable = false)
	public Supplier getSupplier() {
		return this.supplier;
	}

	public void setSupplier(Supplier supplier) {
		this.supplier = supplier;
	}

	@Column(name = "name", nullable = false, length = 250)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "taxnumber", nullable = false, length = 50)
	public String getTaxnumber() {
		return this.taxnumber;
	}

	public void setTaxnumber(String taxnumber) {
		this.taxnumber = taxnumber;
	}

	@Column(name = "type", nullable = false, length = 50)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "description", nullable = false, length = 250)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "supplier")
	public Set<Bank> getBanks() {
		return this.banks;
	}

	public void setBanks(Set<Bank> banks) {
		this.banks = banks;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "supplier")
	public Set<Supplier> getSuppliers() {
		return this.suppliers;
	}

	public void setSuppliers(Set<Supplier> suppliers) {
		this.suppliers = suppliers;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "supplier")
	public Set<Warehouse> getWarehouses() {
		return this.warehouses;
	}

	public void setWarehouses(Set<Warehouse> warehouses) {
		this.warehouses = warehouses;
	}

}
