package comi.entities;
// Generated Jun 9, 2019 4:54:54 PM by Hibernate Tools 5.1.7.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Vendor generated by hbm2java
 */
@Entity
@Table(name = "vendor", catalog = "multivendor")
public class Vendor implements java.io.Serializable {

	private Integer id;
	private Vendor vendor;
	private String name;
	private String taxnumber;
	private String type;
	private String description;
	private Set<Contract> contracts = new HashSet<Contract>(0);
	private Set<Vendor> vendors = new HashSet<Vendor>(0);
	private Set<Bank> banks = new HashSet<Bank>(0);
	private Set<Warehouse> warehouses = new HashSet<Warehouse>(0);

	public Vendor() {
	}

	public Vendor(Vendor vendor, String name, String taxnumber, String type, String description) {
		this.vendor = vendor;
		this.name = name;
		this.taxnumber = taxnumber;
		this.type = type;
		this.description = description;
	}

	public Vendor(Vendor vendor, String name, String taxnumber, String type, String description,
			Set<Contract> contracts, Set<Vendor> vendors, Set<Bank> banks, Set<Warehouse> warehouses) {
		this.vendor = vendor;
		this.name = name;
		this.taxnumber = taxnumber;
		this.type = type;
		this.description = description;
		this.contracts = contracts;
		this.vendors = vendors;
		this.banks = banks;
		this.warehouses = warehouses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "userid", nullable = false)
	public Vendor getVendor() {
		return this.vendor;
	}

	public void setVendor(Vendor vendor) {
		this.vendor = vendor;
	}

	@Column(name = "name", nullable = false, length = 250)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "taxnumber", nullable = false, length = 50)
	public String getTaxnumber() {
		return this.taxnumber;
	}

	public void setTaxnumber(String taxnumber) {
		this.taxnumber = taxnumber;
	}

	@Column(name = "type", nullable = false, length = 50)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "description", nullable = false, length = 250)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "vendor")
	public Set<Contract> getContracts() {
		return this.contracts;
	}

	public void setContracts(Set<Contract> contracts) {
		this.contracts = contracts;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "vendor")
	public Set<Vendor> getVendors() {
		return this.vendors;
	}

	public void setVendors(Set<Vendor> vendors) {
		this.vendors = vendors;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "vendor")
	public Set<Bank> getBanks() {
		return this.banks;
	}

	public void setBanks(Set<Bank> banks) {
		this.banks = banks;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "vendor")
	public Set<Warehouse> getWarehouses() {
		return this.warehouses;
	}

	public void setWarehouses(Set<Warehouse> warehouses) {
		this.warehouses = warehouses;
	}

}
